### ISSUE TITLE
Using two rolls in a macro button for same item that consumes charges only consumes one charge instead of two

### ISSUE THREAD

**Issue by depili** [RedReign/FoundryVTT-BetterRolls5e#121]
With a character that has two attacks I made buttons for two attacks at once. I have setup my thrown weapons to consume charges to keep track of ammunition. If I just copy & paste the same row of code from a macro created by dragging the weapon to the macro bar I get two attacks but only one charge gets consumed.

**Comment by RedReign** [comment]
The issue you're experiencing happens because the roll hasn't quite gone through the first time by the time the second command is rolled. I'd advise against performing multiple rolls as they are asynchronous when your use case requires that they happen one after the other (so that the item charges are successfully updated)
