### ISSUE TITLE
Active abilities usage not consuming uses

### ISSUE THREAD

**Issue by warfric** [RedReign/FoundryVTT-BetterRolls5e#162]
To reproduce:

1. Create a new active ability 
2. Go to Details Tab
2. Set activation cost to "Bonus Action" (anything works really)
3. Set "Limited uses" to 5 of 5 per Long Rest
4. Close editor. 
5. Use ability on character sheet

You will see the Feature used in chat, but the Uses remains at 5/5 no matter how many times you use the ability. Deactivating Better Rolls makes the issue go away. 

Edit: Found work-around/fix? On the Better Rolls tab, you must click the "Consume uses" toggle. Why is this not the default behavior? If there is a resource/use to be used, shouldn't it do that?

**Comment by Sky-Captain-13** [comment]
> Edit: Found work-around/fix? On the Better Rolls tab, you must click the "Consume uses" toggle. Why is this not the default behavior? If there is a resource/use to be used, shouldn't it do that?

Better Rolls doesn't know whether to consume quantity or charges. And it could probably use another setting for consume quantity on zero charges. It would likely be safe to set charges to be auto-consumed but not quantity.

**Comment by CarlosFdez** [comment]
Since the original PR was posted, default properties have changed so that more things consume by default. The problem is that in base foundry it always prompts if you want to consume, and BR tries to remove almost all dialogues. For the alpha version consumables also consume by default (why would they not) but weapons will likely never consume by default.
