### ISSUE TITLE
Permission error in updating OwnedItems

### ISSUE THREAD

**Issue by nhjjreuter** [RedReign/FoundryVTT-BetterRolls5e#173]
Whenever I edit someones character sheet (I've tested this by adding/removing features from the character sheet) all other players receive the error below. I've gone through all of my modules, and the error only seems to occur when better rolls is enabled.

The error, from the perspective of one of my players (Arf) is: `Uncaught (in promise) Error: User Arf lacks permission to update OwnedItems in parent bmdPn66sWFVbJqOJ at Function._onUpdate (C:\Program Files\FoundryVTT\resources\app\dist\database\odm\embedded.js:1:7963)`

**Comment by AnEnemyChampion** [comment]
I am also encountering this issue with my players. This error only occurs with the Better Rolls module enabled.

To replicate the issue:
1. Load up Foundry VTT and host a world that uses Better Roles 5e
2. Join that same world through your invitation link and log in as a player
3. Using the GM account, create a PC that the player does not have any permissions for, then add an "Acid (vial)" from the Items compendium. 

You should be able to see the error message appear on the Player's window but not the GM's window. 

This issue seems to only occur with some items. For example, adding an Abacus does not provoke this error, but Adamantine Armor does.

**Comment by CarlosFdez** [comment]
Thanks for this, I was having this issue but didn't know from where or how to replicate it. Might make a PR since its actually something I can try to deal with, once I know exactly *where* its coming from (it might be a side effect from either active effects or flag setting).

**Comment by MrPrimate** [comment]
Players experience this when using the ddb-importer or vtta-dndbeyond as well when a character is imported. Both of these modules attempt to add some better rolls flag data to items/spells etc.

**Comment by CarlosFdez** [comment]
This problem should now be resolved. Make a new issue if you still have this issue.
