### ISSUE TITLE
Compatibility Issue with Skill Customization 5e

### ISSUE THREAD

**Issue by olavmueller** [RedReign/FoundryVTT-BetterRolls5e#180]
When I add a bonus into a skill for Skill Customization for 5e (+10 for example for a Stealth check under Pass without a trace) this bonus is not applied to the Better Rolls roll. I don't know whether this is a BR or a SC problem. (I'm submitting the same issue over there...)

**Comment by CarlosFdez** [comment]
This should work in the development (alpha) version of Better Rolls. If you need the two to work together give it a shot. Its possible for things to break between releases but trying to keep it at a minimum since I use it in my games:

https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/tag/v1.2.alpha.4

You'll also need the newest version of Skill Customization, they actually fixed something to allow it to work.

**Comment by olavmueller** [comment]
Thanks, this seems to have done it. Works for me.
