### ISSUE TITLE
Suggestion: Add active effect contexts to damage labels when available

### ISSUE THREAD

**Issue by crash1115** [RedReign/FoundryVTT-BetterRolls5e#193]
**Use Case (for context)**
I've got a couple active effects set up that add damage for things like Booming Blade and the Eldritch Claw tattoo from Tasha's. These both are set to add damage to the appropriate kinds of attacks, and they make use of the ability to use square brackets to add context to those values (eg `+1d8[Thunder]` for Booming Blade).

**Issue**
When using BR, all that damage is combined under one section, but the label for that damage segment only communicates whatever is listed in the item for damage type and doesn't take into account additional sources. This leads to a chat card that looks like this:

![image](https://user-images.githubusercontent.com/41387713/104366696-c2f5cf80-54e7-11eb-9b0d-176462abf9bd.png)

Yes, you can expand the damage roll to get specifics for those additional contexts, but it'd be great if there was some indicator in the section label that implied there was more than one type of damage included in the section in the first place. In this case, it'd read like this: `Level 2 - Psychic, Thunder, Force`

===

Reference screenshots

![image](https://user-images.githubusercontent.com/41387713/104367214-7d85d200-54e8-11eb-8110-89a429c0ad9b.png)
![image](https://user-images.githubusercontent.com/41387713/104367323-a60dcc00-54e8-11eb-9c2b-f027dea1c1c8.png)

**Comment by crash1115** [comment]
Come to think of it, an alternative solution (one might be easier than the other) is to just have different sections entirely for any damage added through active effects, with context labels as appropriate.

**Comment by CarlosFdez** [comment]
Interestingly enough, I had to disable DAE first. Seems that the dropdown doesn't list "Add" as an option for that property.

Hmm, so in other words, your suggestion is to add a new damage row if the type coming in from active effects is labeled? Makes sense to me, though I will say that I have no idea how to detect that the bonus is happening nor where its coming from. Currently bonuses come from Actor.getRollData() and then rollData.bonuses[weaponType] which are all squashed together. So for example, in the case you've listed (2 different effects):
![image](https://user-images.githubusercontent.com/1286721/104374732-516e4f00-54f0-11eb-90d7-4d410b99eb7b.png)

Detecting that each bonus comes from a different effect or that its even typed might be a bit of a stretch. In fact the only way I see to find those context labels is to dig into the roll object after its combined, go over the dice terms, and get options.flavor for the dice term. Then check the previous term and ensure its a + because anything else and I will seriously need to consider building an AST.

If you or anyone else knows more about the Foundry API sufficiently enough to tackle this, I'd certainly appreciate the help. Its not a feature I'd end up using so I really wouldn't be able to give it the research it needs. Its very likely that your first idea (add additional context labels to the header) might be the only way to do it with what Foundry has given us.

**Comment by crash1115** [comment]
> Hmm, so in other words, your suggestion is to add a new damage row if the type coming in from active effects is labeled? 

Yeah, pretty much just this.

> Detecting that each bonus comes from a different effect or that its even typed might be a bit of a stretch.

You might not even have to go that far. Splitting the string into terms (using `+` as a delimiter) and making each one its own line would probably be enough. If there's context associated with it, use that as the row label. If not, just leave it blank. I could definitely see edge cases popping up where a single effect does something like `+1d10+5[Radiant]` though, so maybe that's not the best solution. One alternative might be to do a single additional line that tallies up all the bonus damage. 

> Its very likely that your first idea (add additional context labels to the header) might be the only way to do it with what Foundry has given us.

This is also fine. I think midi does this, and it's enough of a "hey! there's more damage types in here!" to get you to expand the roll and see what's there. That's really all I think needs to be present.

**Comment by CarlosFdez** [comment]
I think for now that's what I might end up doing. I'm a bit concerned with the edgecases of doing anything more complicated especially so close to a new release (new alpha is basically a release candidate) and on something that Foundry is likely to handle in the future anyways. If there's an API to iterate over all active effect sources for a property it would be nice though.

If someone wants to try their luck at splitting it though, it'd certainly help. RollFields.constructDamageRoll() would have to return an array instead and perform the split in there. Alternatively, roll bonuses should be handled as a new "bonus" field type and bonuses completely removed from constructDamageRoll(), but it would need to not make flat rolls any more difficult (dueling/rage are common). 

For my own uses, I was thinking of creating a method that leverages the rollItemBetterRolls or preRollBetterRolls hook to add new damage rows to a roll similarly to how Roll20 allows you to do so, but unfortunately it would require some sheet buy-in, or some fancy macro business. Would much rather the active effect macro split the more I think of it. 

Could also cheat and add a new ActiveEffect key type specific to better rolls and iterate over the effects or something.

**Comment by crash1115** [comment]
> If someone wants to try their luck at splitting it though (in branch development), it'd certainly help.

I can take a look at this later this week when I have some time, just for the hell of it.

> Could also cheat and add a new ActiveEffect key type specific to better rolls and iterate over the effects or something.

Yeah, this is along the lines of what I would do. That, or using active effects to set BR-specific actor flags and then using those to construct the new damage rows. Both ways probably have their merits.

**Comment by CarlosFdez** [comment]
Another set of eyes on the codebase would help in more ways than one. Part of this refactor was to try to improve readability however without a constant set of eyes its pretty easy to slip somewhere along the way.

Currently I'm pushing this out in the meantime.
![image](https://user-images.githubusercontent.com/1286721/104387591-74572e00-5505-11eb-8e7a-148782857c99.png)

Piercing showing twice is because these are contexts, and Piercing is a damage type. If the context is Piercing then it won't show the duplicate context.
