### ISSUE TITLE
Feature save DC not calculating correctly, measured template not auto-placing

### ISSUE THREAD

**Issue by adacosta92** [RedReign/FoundryVTT-BetterRolls5e#202]
![image](https://user-images.githubusercontent.com/67127175/105802578-78edfe80-5f69-11eb-9913-636d8f17dfbf.png)

i have an item that's not calling the save DC properly. in the first instance in the chat, i've set the DC to 15 (flat). In the second, i've set it to spellcasting (which is supposed to be 15). either way, the item card shows it as 15, but in the second, the chat card calls it as 11. 

betterrolls5e also doesn't place a measurement template for features with one, and also isn't calculating the save DC correctly in the chat card.

**Comment by CarlosFdez** [comment]
Actually just saw this in the discord. Definitely something I should look into soon.

Regarding measurement controls and save dcs, most things should do them now by default. Could it be an old item from before I updated the defaults? Old items do not get their defaults changed. If you look into the Better Rolls tab you'll see a button that enables them to show, since its possible for an alt roll to have different settings from a main roll (ex: main roll consumes bardic inspiration, alt rolls it and does not consume).

**Comment by adacosta92** [comment]
That was it regarding the template, thanks. DC is still 11 when it should be 15 though. thanks for the quick response!

**Comment by CarlosFdez** [comment]
Yeah DC part is a bug. I need to tackle it while also tackling vehicles, but I'm waiting for when I get some free time before I look into it (so probably this weekend).

**Comment by CarlosFdez** [comment]
Should be fixed in 1.3.5. Thanks for reporting.

**Comment by adacosta92** [comment]
> Should be fixed in 1.3.5. Thanks for reporting.

Yeah no problem! Thanks for making this module!
