### ISSUE TITLE
Charge abilities not spending its charges

### ISSUE THREAD

**Issue by VMCorrea** [RedReign/FoundryVTT-BetterRolls5e#203]
Greetings.

I've noticed recently that charged features, like breath weapons, are not spending charges like they should.

Didn't overly tested with every module combination.

Foundry 0.7.9
DnD5e 1.2.4
Better Rolls 1.3.4

[modules.txt](https://github.com/RedReign/FoundryVTT-BetterRolls5e/files/5875373/modules.txt)

**Comment by CarlosFdez** [comment]
If its an old dragon breath entry, that's because the old default setting was not to consume charges unless enabled. Go into the Better Rolls setting while editing the feature, and enable uses consumption.

Newly imported actors will have uses consumption enabled by default (unless its a weapon, weapons are disabled by default).

**Comment by VMCorrea** [comment]
That's it. Thanks.
