### ISSUE TITLE
Error message "No actor/item known that that ID" spams

### ISSUE THREAD

**Issue by megahead11** [RedReign/FoundryVTT-BetterRolls5e#231]
When relogging, sometimes the error message "No actor known that that ID" or "No item known with that ID" will spam when referencing an item that no longer exists when an actor's token is deleted (mainly NPCs it seems) if that token was deleted prior to a reload.

When this message appears, it will do so for each instance of a chat roll from said actor, spamming the above messages. In some rare circumstances, this causes my players to crash because of "out of memory issues"

**Comment by CarlosFdez** [comment]
This seems decently high priority, so will tackle it first thing tomorrow morning. Thanks for reporting.

**Comment by CarlosFdez** [comment]
That said, before I go deep into it, anything special you're doing to produce this? Are you using it with midi? TBH I never ran into this issue.

**Comment by megahead11** [comment]
Yeah, does appear to happen consistently with Midi-Qol

**Comment by megahead11** [comment]
Forgot to mention, but clearing the chat log will prevent these messages from appearing on subsequent reloads.

**Comment by CarlosFdez** [comment]
On the newest version it should prevent these errors in the meantime, though I'm uncertain about the memory problems some of your players had. Midi accesses the item on a better rolls card for EVERY card on the list, which caches the item. I'm toying with the idea of tweaking the API so that it doesn't cache the items, but no clue on how to do that quite yet (though I do have an idea), but it seems like @tposney is looking into using just the item id.

**Comment by tposney** [comment]
Next version of midi will only access the item if the activate effects
button is pressed. So should be almost never
