### ISSUE TITLE
Reliable Talent doesn't work with tools

### ISSUE THREAD

**Issue by crash1115** [RedReign/FoundryVTT-BetterRolls5e#232]
Pretty much just the title. Works okay with skills, should also work with tools, per RAW. 

![image](https://user-images.githubusercontent.com/41387713/110068052-e64c3680-7d42-11eb-89eb-ab0d0dca39e8.png)

**Comment by CarlosFdez** [comment]
It should yeah, but it seems like in core 5e it also doesn't work. I was tempted on seeing if I can make tool rolls use core 5e as part of my attempt to improve compatibility but it wouldn't fix this issue if I did.

**Comment by crash1115** [comment]
That's odd. They work in core for me. Top 2 chat cards in the screenshot are zero mods enabled vanilla 5e, and it's applying correctly.

**Comment by CarlosFdez** [comment]
You're correct, its because newly added tools are non-proficient by default. Then sure, I'll start looking into it asap, thanks for reporting.

**Comment by CarlosFdez** [comment]
Fixed in master, but waiting on some fixes from Midi before releasing. As part of the changes I now identify advantage/disadvantage from the formula itself when coming from an item/tool/skill, which fixes one bug with midi but introduces another.

Quite a bit is changing internally with this release, so fingers crossed.

**Comment by CarlosFdez** [comment]
Fix is released. Let me know if it works, and if there's any other issues.
