### ISSUE TITLE
Midi QOL incompatibility

### ISSUE THREAD

**Issue by celicynd** [RedReign/FoundryVTT-BetterRolls5e#246]
Since the 1.4.0 version,  Better Rolls, when clicking the item icon from character sheet, seems to be popping up the window where you can adjust the die formula and choose advantage, normal or disadvantage.  If I disable Midi QOL, or I go back to 1.3.13, the issue goes away. I thought it might be another module causing issue, but I've disabled all but whats needed for BetterRolls and Midi, and still have this issue. 
![rollwindow](https://user-images.githubusercontent.com/81255301/112192958-d0ad8c80-8bdd-11eb-9ea7-e0c03bdffa4c.png)

**Comment by zacdemon** [comment]
I had this issue before. Uncheck enable roll automation in MIDI and it should go away.
![image](https://user-images.githubusercontent.com/22028379/112195342-3bf85e00-8be0-11eb-8d7d-cc080acecd27.png)

**Comment by CarlosFdez** [comment]
And unfortunately that's not something that can be fixed on my end. that happens because midi is ignoring the fast forward and advantage/disadvantage parameters. Midi is a big project and there's a lot of moving parts, and they can't really fix it without some refactoring, at least from my glances into the codebase.

**Comment by celicynd** [comment]
Turns out you can turn on enable fast forward rolls in Midi to get this to not enable. For some reason when I was trying to get it to work, I missed that setting.
