### ISSUE TITLE
Optional (Settings) add target[s] to chat card

### ISSUE THREAD

**Issue by Lazytron** [RedReign/FoundryVTT-BetterRolls5e#251]
MESS did this and it was very helpful.

**Comment by CarlosFdez** [comment]
MESS has been superceded by MARS if I recall correctly, though I think midi does add that feature to better rolls.

The problem is that Better Rolls is not an automation suite, its a replacement for the core roller. Stuff like targets are not a feature in the core roller, and lead to conflicting UX because damage buttons don't use targets, they use selection. As players can't select enemies, that means some features use selection, and some use targets, and targets are not something ever well explained in foundry.

Also if I were to add that stuff, midi's integration would go extra highwire. :^)

**Comment by Lazytron** [comment]
Fair enough!
