### ISSUE TITLE
Max Base + Max Critical issue

### ISSUE THREAD

**Issue by dnf257** [RedReign/FoundryVTT-BetterRolls5e#255]
Having an issue getting the Max Base + Max Critical option to work. It happened pretty much randomly, didn't install anything new.
https://i.imgur.com/h0DsgfC.png

**Comment by dnf257** [comment]
Also noticed this issue with the apply crit damage popup box `https://i.imgur.com/eopsF7a.jpg`

**Comment by Stendarpaval** [comment]
@dnf257 Saw your reddit thread on /r/Foundry and decided to reply here instead.

I can replicate your issue with Fire Bolt (though it really helps to also describe it rather than just sharing two pictures).

The issue with the Critical Damage setting set to "Max Base + Max Critical" is that the Max Critical damage is (erroneously) calculated as `(Max Base damage + Max Critical damage) - rolled base damage`. So in the case of your Fire Bolt screenshot, this would be `(20 + 20) - 13 = 27`. 

This is incorrect, as it should be `rolled base damage + Max  Critical Damage`, or in case of the same example `13 + 20 = 33`. 

I cannot replicate your second screenshot, because I don't know what damage formula that weapon uses. I tried it out with a Skeleton's Shortbow attack, and it worked as it should. Maybe your weapon has a magical damage bonus being added to it?
