### ISSUE TITLE
Last consumed Ammunition doesn't give Attack Bonus

### ISSUE THREAD

**Issue by RufusTiki** [RedReign/FoundryVTT-BetterRolls5e#286]
Hello, it seems when you only have one special ammunition left it gives the damage bonus but not the attack bonus. Turned off BetterRolls and tested against default system to be sure.

Steps:
- Add "Arrows +1" and set quantity to 2 or more.
- Set Weapon to use Arrows +1.
- Attack. When you are down to 1 Arrow you lose the +1 attack bonus. When you are at 0 Arrows it correctly alerts you.

Stepped through the code but couldn't figure out where the error may be.
Thanks!

**Comment by CarlosFdez** [comment]
I'll check this out soon, but I do have some things I'm messing with. I suspect though that the fields aren't receiving the ammo item because its getting deleted beforehand, but the damage field has already created. Its probably in the default parameter population for the fields.

**Comment by CarlosFdez** [comment]
Definitely big sorry for lateness regarding this. Big splatbook is coming out soon for pathfinder 2e and that's kept me busy.

I suspect that the bug is because the ammo is tested and wiped within the same function (CustomItemRoll.consumeAmmo()) and the 5e system does not add the ammo item bonus if the ammo's quantity is 0 or consumed or what have you. I'll need to somehow break up ammo update so that the ammo doesn't get consumed until after the attack is rolled. Will get on that soon, hopefully for real this time.

**Comment by CarlosFdez** [comment]
Should be fixed now. I pushed it alongside another fix for 0.8.8.
