### ISSUE TITLE
Critical damage calculation for secondary damage formula is incorrect

### ISSUE THREAD

**Issue by ralph2190** [RedReign/FoundryVTT-BetterRolls5e#360]
Hey there. I'm currently on Foundry v0.8.9 and using Better Rolls v1.7.1. I've noticed that the Player view of the critical damage dice roll does not match what the DM sees, when secondary damage formulas are involved. Apparently, the player is only seeing the first damage formula's crit repeated for the second damage formula. See the attached pic for reference.
<img width="439" alt="better_rolls_bug" src="https://user-images.githubusercontent.com/11889617/149252719-a2c3d641-db47-4073-b09c-f7bf9927d2f4.png">

**Comment by hafdon** [comment]
I'm having (i think the same) issue where if you click the "+" (crit) button on damage, and have Max Base Damage, Roll Critical Damage" selected in settings, it _rolls_ the crit damage rather than maximizing any dice in that roll. I've included monster screenshots,
I've tried this with the world system settings set at both Critical Damage Maximize dice true and false.

foundry 9.242
better rolls 1.7.1
dnd 1.5.7
chrome, windows 10

![image](https://user-images.githubusercontent.com/39073287/151104232-085345b4-b965-4cf0-b421-18e31a796bae.png)

![image](https://user-images.githubusercontent.com/39073287/151104181-e4c7e56f-b1a8-4bc5-8a45-25538b7c6662.png)

**Comment by ralph2190** [comment]
Cannot repro in release 1.7.2. Closing.
![image](https://user-images.githubusercontent.com/11889617/165593713-dd685c2d-65f0-41ce-8da9-58ce539fc30e.png)
