### ISSUE TITLE
Use target for chat damage buttons instead of selected tokens for non-DM players

### ISSUE THREAD

**Issue by Sciguymjm** [RedReign/FoundryVTT-BetterRolls5e#9]
Or don't show chat damage buttons to players at all, since they can't select other tokens to apply damage / healing.

If selecting other tokens is something that can be enabled, do let me know.

**Comment by RedReign** [comment]
The buttons are there for you to apply to your *own* tokens. You would usually do this on an enemy's attack. The DM would then use those damage buttons on enemies that you target with your attacks.

This is by design, as there are a lot of things that can prevent/reduce damage that are not yet automated in foundry, so a player should not be able to force damage to apply to tokens.

**Comment by Sciguymjm** [comment]
Makes sense. Thanks!
